version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: gamehub_db
    restart: always
    environment:
      MYSQL_DATABASE: gamehub
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - "3306:3306"
    volumes:
      - ./database:/docker-entrypoint-initdb.d  # Autoejecuta el init.sql de Rubén

  backend:
    image: python:3.10-slim
    container_name: gamehub_backend
    restart: always
    volumes:
      - ./backend:/app
    working_dir: /app
    command: sh -c "pip install -r requirements.txt && python app/main.py"
    ports:
      - "8000:8000"
    depends_on:
      - db

  frontend:
    image: node:18-alpine
    container_name: gamehub_frontend
    restart: always
    volumes:
      - ./gamehub-ecosystem:/app  # Apunta a la carpeta donde está tu código React
    working_dir: /app
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0"
    ports:
      - "5173:5173"
    environment:
      - VITE_API_BASE_URL=http://localhost:8000 # Para que se conecte al backend local
    depends_on:
      - backend